name: ip_sniffer

on:
  push:
    branches: [master]

jobs:
  ip_sniffer:
    name: ip_sniffer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - name: Test
        run: npm test
      - name: Build
        run: npm build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
